package com.mvw.medicalvisualteaching.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mvw.medicalvisualteaching.bean.offlinebook.AuthorItemContents;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "AuthorItem_contents".
*/
public class AuthorItemContentsDao extends AbstractDao<AuthorItemContents, Void> {

    public static final String TABLENAME = "AuthorItem_contents";

    /**
     * Properties of entity AuthorItemContents.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property AuthorItem_id = new Property(0, String.class, "AuthorItem_id", false, "AuthorItem_id");
        public final static Property Contents = new Property(1, String.class, "contents", false, "contents");
    }


    public AuthorItemContentsDao(DaoConfig config) {
        super(config);
    }
    
    public AuthorItemContentsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AuthorItemContents entity) {
        stmt.clearBindings();
 
        String AuthorItem_id = entity.getAuthorItem_id();
        if (AuthorItem_id != null) {
            stmt.bindString(1, AuthorItem_id);
        }
 
        String contents = entity.getContents();
        if (contents != null) {
            stmt.bindString(2, contents);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AuthorItemContents entity) {
        stmt.clearBindings();
 
        String AuthorItem_id = entity.getAuthorItem_id();
        if (AuthorItem_id != null) {
            stmt.bindString(1, AuthorItem_id);
        }
 
        String contents = entity.getContents();
        if (contents != null) {
            stmt.bindString(2, contents);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public AuthorItemContents readEntity(Cursor cursor, int offset) {
        AuthorItemContents entity = new AuthorItemContents( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // AuthorItem_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // contents
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AuthorItemContents entity, int offset) {
        entity.setAuthorItem_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setContents(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(AuthorItemContents entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(AuthorItemContents entity) {
        return null;
    }

    @Override
    public boolean hasKey(AuthorItemContents entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
