package com.mvw.medicalvisualteaching.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mvw.medicalvisualteaching.bean.offlinebook.AuthorTitle;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "Author_title".
*/
public class AuthorTitleDao extends AbstractDao<AuthorTitle, Void> {

    public static final String TABLENAME = "Author_title";

    /**
     * Properties of entity AuthorTitle.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Author_id = new Property(0, String.class, "Author_id", false, "Author_id");
        public final static Property Title = new Property(1, String.class, "title", false, "title");
    }


    public AuthorTitleDao(DaoConfig config) {
        super(config);
    }
    
    public AuthorTitleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AuthorTitle entity) {
        stmt.clearBindings();
 
        String Author_id = entity.getAuthor_id();
        if (Author_id != null) {
            stmt.bindString(1, Author_id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AuthorTitle entity) {
        stmt.clearBindings();
 
        String Author_id = entity.getAuthor_id();
        if (Author_id != null) {
            stmt.bindString(1, Author_id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public AuthorTitle readEntity(Cursor cursor, int offset) {
        AuthorTitle entity = new AuthorTitle( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // Author_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // title
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AuthorTitle entity, int offset) {
        entity.setAuthor_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(AuthorTitle entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(AuthorTitle entity) {
        return null;
    }

    @Override
    public boolean hasKey(AuthorTitle entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
