package com.mvw.medicalvisualteaching.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mvw.medicalvisualteaching.bean.offlinebook.CombinationItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CombinationItem".
*/
public class CombinationItemDao extends AbstractDao<CombinationItem, Void> {

    public static final String TABLENAME = "CombinationItem";

    /**
     * Properties of entity CombinationItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", false, "id");
        public final static Property Name = new Property(1, String.class, "name", false, "name");
        public final static Property Picture = new Property(2, String.class, "picture", false, "picture");
        public final static Property MediaCombination_id = new Property(3, String.class, "mediaCombination_id", false, "mediaCombination_id");
    }


    public CombinationItemDao(DaoConfig config) {
        super(config);
    }
    
    public CombinationItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CombinationItem entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String picture = entity.getPicture();
        if (picture != null) {
            stmt.bindString(3, picture);
        }
 
        String mediaCombination_id = entity.getMediaCombination_id();
        if (mediaCombination_id != null) {
            stmt.bindString(4, mediaCombination_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CombinationItem entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String picture = entity.getPicture();
        if (picture != null) {
            stmt.bindString(3, picture);
        }
 
        String mediaCombination_id = entity.getMediaCombination_id();
        if (mediaCombination_id != null) {
            stmt.bindString(4, mediaCombination_id);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public CombinationItem readEntity(Cursor cursor, int offset) {
        CombinationItem entity = new CombinationItem( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // picture
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // mediaCombination_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CombinationItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPicture(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMediaCombination_id(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(CombinationItem entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(CombinationItem entity) {
        return null;
    }

    @Override
    public boolean hasKey(CombinationItem entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
