package com.mvw.medicalvisualteaching.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mvw.medicalvisualteaching.bean.Book;
import com.mvw.medicalvisualteaching.bean.Exam;
import com.mvw.medicalvisualteaching.bean.offlinebook.Author;
import com.mvw.medicalvisualteaching.bean.offlinebook.AuthorItem;
import com.mvw.medicalvisualteaching.bean.offlinebook.AuthorItemContents;
import com.mvw.medicalvisualteaching.bean.offlinebook.AuthorTitle;
import com.mvw.medicalvisualteaching.bean.offlinebook.Chapter;
import com.mvw.medicalvisualteaching.bean.offlinebook.Colleges;
import com.mvw.medicalvisualteaching.bean.offlinebook.CombinationItem;
import com.mvw.medicalvisualteaching.bean.offlinebook.Committee;
import com.mvw.medicalvisualteaching.bean.offlinebook.Editors;
import com.mvw.medicalvisualteaching.bean.offlinebook.KeyWord;
import com.mvw.medicalvisualteaching.bean.offlinebook.LocalBook;
import com.mvw.medicalvisualteaching.bean.offlinebook.MediaBlock;
import com.mvw.medicalvisualteaching.bean.offlinebook.MediaPPTItem;
import com.mvw.medicalvisualteaching.bean.offlinebook.Medias;
import com.mvw.medicalvisualteaching.bean.offlinebook.MediaSequence;
import com.mvw.medicalvisualteaching.bean.offlinebook.MediaSequencePictures;
import com.mvw.medicalvisualteaching.bean.offlinebook.MediaStaticSequencePictures;
import com.mvw.medicalvisualteaching.bean.offlinebook.MediaVideo;
import com.mvw.medicalvisualteaching.bean.offlinebook.Paragraph;
import com.mvw.medicalvisualteaching.bean.offlinebook.ParagraphAuthor;
import com.mvw.medicalvisualteaching.bean.offlinebook.Section;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionAcknowledgements;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionBackCover;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionCaseSection;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionCasesItem;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionCasesItemAuthors;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionCETranslate;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionCover;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionDetail;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionDocument;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionDocumentItem;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionImprint;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionImprintEditor;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionLearningCenter;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionMainPoints;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionNameList;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionParagraph;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionPreface;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionPrefaceTitle;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionReference;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionShorthand;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionSummary;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionSummaryChinese;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionSummaryEnglish;
import com.mvw.medicalvisualteaching.bean.offlinebook.SectionTranslate;
import com.mvw.medicalvisualteaching.bean.offlinebook.TableView;
import com.mvw.medicalvisualteaching.bean.offlinebook.TDView;
import com.mvw.medicalvisualteaching.bean.offlinebook.TRView;
import com.mvw.medicalvisualteaching.bean.User;
import com.mvw.medicalvisualteaching.bean.UserBook;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDaoConfig;
    private final DaoConfig examDaoConfig;
    private final DaoConfig authorDaoConfig;
    private final DaoConfig authorItemDaoConfig;
    private final DaoConfig authorItemContentsDaoConfig;
    private final DaoConfig authorTitleDaoConfig;
    private final DaoConfig chapterDaoConfig;
    private final DaoConfig collegesDaoConfig;
    private final DaoConfig combinationItemDaoConfig;
    private final DaoConfig committeeDaoConfig;
    private final DaoConfig editorsDaoConfig;
    private final DaoConfig keyWordDaoConfig;
    private final DaoConfig localBookDaoConfig;
    private final DaoConfig mediaBlockDaoConfig;
    private final DaoConfig mediaPPTItemDaoConfig;
    private final DaoConfig mediasDaoConfig;
    private final DaoConfig mediaSequenceDaoConfig;
    private final DaoConfig mediaSequencePicturesDaoConfig;
    private final DaoConfig mediaStaticSequencePicturesDaoConfig;
    private final DaoConfig mediaVideoDaoConfig;
    private final DaoConfig paragraphDaoConfig;
    private final DaoConfig paragraphAuthorDaoConfig;
    private final DaoConfig sectionDaoConfig;
    private final DaoConfig sectionAcknowledgementsDaoConfig;
    private final DaoConfig sectionBackCoverDaoConfig;
    private final DaoConfig sectionCaseSectionDaoConfig;
    private final DaoConfig sectionCasesItemDaoConfig;
    private final DaoConfig sectionCasesItemAuthorsDaoConfig;
    private final DaoConfig sectionCETranslateDaoConfig;
    private final DaoConfig sectionCoverDaoConfig;
    private final DaoConfig sectionDetailDaoConfig;
    private final DaoConfig sectionDocumentDaoConfig;
    private final DaoConfig sectionDocumentItemDaoConfig;
    private final DaoConfig sectionImprintDaoConfig;
    private final DaoConfig sectionImprintEditorDaoConfig;
    private final DaoConfig sectionLearningCenterDaoConfig;
    private final DaoConfig sectionMainPointsDaoConfig;
    private final DaoConfig sectionNameListDaoConfig;
    private final DaoConfig sectionParagraphDaoConfig;
    private final DaoConfig sectionPrefaceDaoConfig;
    private final DaoConfig sectionPrefaceTitleDaoConfig;
    private final DaoConfig sectionReferenceDaoConfig;
    private final DaoConfig sectionShorthandDaoConfig;
    private final DaoConfig sectionSummaryDaoConfig;
    private final DaoConfig sectionSummaryChineseDaoConfig;
    private final DaoConfig sectionSummaryEnglishDaoConfig;
    private final DaoConfig sectionTranslateDaoConfig;
    private final DaoConfig tableViewDaoConfig;
    private final DaoConfig tDViewDaoConfig;
    private final DaoConfig tRViewDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig userBookDaoConfig;

    private final BookDao bookDao;
    private final ExamDao examDao;
    private final AuthorDao authorDao;
    private final AuthorItemDao authorItemDao;
    private final AuthorItemContentsDao authorItemContentsDao;
    private final AuthorTitleDao authorTitleDao;
    private final ChapterDao chapterDao;
    private final CollegesDao collegesDao;
    private final CombinationItemDao combinationItemDao;
    private final CommitteeDao committeeDao;
    private final EditorsDao editorsDao;
    private final KeyWordDao keyWordDao;
    private final LocalBookDao localBookDao;
    private final MediaBlockDao mediaBlockDao;
    private final MediaPPTItemDao mediaPPTItemDao;
    private final MediasDao mediasDao;
    private final MediaSequenceDao mediaSequenceDao;
    private final MediaSequencePicturesDao mediaSequencePicturesDao;
    private final MediaStaticSequencePicturesDao mediaStaticSequencePicturesDao;
    private final MediaVideoDao mediaVideoDao;
    private final ParagraphDao paragraphDao;
    private final ParagraphAuthorDao paragraphAuthorDao;
    private final SectionDao sectionDao;
    private final SectionAcknowledgementsDao sectionAcknowledgementsDao;
    private final SectionBackCoverDao sectionBackCoverDao;
    private final SectionCaseSectionDao sectionCaseSectionDao;
    private final SectionCasesItemDao sectionCasesItemDao;
    private final SectionCasesItemAuthorsDao sectionCasesItemAuthorsDao;
    private final SectionCETranslateDao sectionCETranslateDao;
    private final SectionCoverDao sectionCoverDao;
    private final SectionDetailDao sectionDetailDao;
    private final SectionDocumentDao sectionDocumentDao;
    private final SectionDocumentItemDao sectionDocumentItemDao;
    private final SectionImprintDao sectionImprintDao;
    private final SectionImprintEditorDao sectionImprintEditorDao;
    private final SectionLearningCenterDao sectionLearningCenterDao;
    private final SectionMainPointsDao sectionMainPointsDao;
    private final SectionNameListDao sectionNameListDao;
    private final SectionParagraphDao sectionParagraphDao;
    private final SectionPrefaceDao sectionPrefaceDao;
    private final SectionPrefaceTitleDao sectionPrefaceTitleDao;
    private final SectionReferenceDao sectionReferenceDao;
    private final SectionShorthandDao sectionShorthandDao;
    private final SectionSummaryDao sectionSummaryDao;
    private final SectionSummaryChineseDao sectionSummaryChineseDao;
    private final SectionSummaryEnglishDao sectionSummaryEnglishDao;
    private final SectionTranslateDao sectionTranslateDao;
    private final TableViewDao tableViewDao;
    private final TDViewDao tDViewDao;
    private final TRViewDao tRViewDao;
    private final UserDao userDao;
    private final UserBookDao userBookDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        examDaoConfig = daoConfigMap.get(ExamDao.class).clone();
        examDaoConfig.initIdentityScope(type);

        authorDaoConfig = daoConfigMap.get(AuthorDao.class).clone();
        authorDaoConfig.initIdentityScope(type);

        authorItemDaoConfig = daoConfigMap.get(AuthorItemDao.class).clone();
        authorItemDaoConfig.initIdentityScope(type);

        authorItemContentsDaoConfig = daoConfigMap.get(AuthorItemContentsDao.class).clone();
        authorItemContentsDaoConfig.initIdentityScope(type);

        authorTitleDaoConfig = daoConfigMap.get(AuthorTitleDao.class).clone();
        authorTitleDaoConfig.initIdentityScope(type);

        chapterDaoConfig = daoConfigMap.get(ChapterDao.class).clone();
        chapterDaoConfig.initIdentityScope(type);

        collegesDaoConfig = daoConfigMap.get(CollegesDao.class).clone();
        collegesDaoConfig.initIdentityScope(type);

        combinationItemDaoConfig = daoConfigMap.get(CombinationItemDao.class).clone();
        combinationItemDaoConfig.initIdentityScope(type);

        committeeDaoConfig = daoConfigMap.get(CommitteeDao.class).clone();
        committeeDaoConfig.initIdentityScope(type);

        editorsDaoConfig = daoConfigMap.get(EditorsDao.class).clone();
        editorsDaoConfig.initIdentityScope(type);

        keyWordDaoConfig = daoConfigMap.get(KeyWordDao.class).clone();
        keyWordDaoConfig.initIdentityScope(type);

        localBookDaoConfig = daoConfigMap.get(LocalBookDao.class).clone();
        localBookDaoConfig.initIdentityScope(type);

        mediaBlockDaoConfig = daoConfigMap.get(MediaBlockDao.class).clone();
        mediaBlockDaoConfig.initIdentityScope(type);

        mediaPPTItemDaoConfig = daoConfigMap.get(MediaPPTItemDao.class).clone();
        mediaPPTItemDaoConfig.initIdentityScope(type);

        mediasDaoConfig = daoConfigMap.get(MediasDao.class).clone();
        mediasDaoConfig.initIdentityScope(type);

        mediaSequenceDaoConfig = daoConfigMap.get(MediaSequenceDao.class).clone();
        mediaSequenceDaoConfig.initIdentityScope(type);

        mediaSequencePicturesDaoConfig = daoConfigMap.get(MediaSequencePicturesDao.class).clone();
        mediaSequencePicturesDaoConfig.initIdentityScope(type);

        mediaStaticSequencePicturesDaoConfig = daoConfigMap.get(MediaStaticSequencePicturesDao.class).clone();
        mediaStaticSequencePicturesDaoConfig.initIdentityScope(type);

        mediaVideoDaoConfig = daoConfigMap.get(MediaVideoDao.class).clone();
        mediaVideoDaoConfig.initIdentityScope(type);

        paragraphDaoConfig = daoConfigMap.get(ParagraphDao.class).clone();
        paragraphDaoConfig.initIdentityScope(type);

        paragraphAuthorDaoConfig = daoConfigMap.get(ParagraphAuthorDao.class).clone();
        paragraphAuthorDaoConfig.initIdentityScope(type);

        sectionDaoConfig = daoConfigMap.get(SectionDao.class).clone();
        sectionDaoConfig.initIdentityScope(type);

        sectionAcknowledgementsDaoConfig = daoConfigMap.get(SectionAcknowledgementsDao.class).clone();
        sectionAcknowledgementsDaoConfig.initIdentityScope(type);

        sectionBackCoverDaoConfig = daoConfigMap.get(SectionBackCoverDao.class).clone();
        sectionBackCoverDaoConfig.initIdentityScope(type);

        sectionCaseSectionDaoConfig = daoConfigMap.get(SectionCaseSectionDao.class).clone();
        sectionCaseSectionDaoConfig.initIdentityScope(type);

        sectionCasesItemDaoConfig = daoConfigMap.get(SectionCasesItemDao.class).clone();
        sectionCasesItemDaoConfig.initIdentityScope(type);

        sectionCasesItemAuthorsDaoConfig = daoConfigMap.get(SectionCasesItemAuthorsDao.class).clone();
        sectionCasesItemAuthorsDaoConfig.initIdentityScope(type);

        sectionCETranslateDaoConfig = daoConfigMap.get(SectionCETranslateDao.class).clone();
        sectionCETranslateDaoConfig.initIdentityScope(type);

        sectionCoverDaoConfig = daoConfigMap.get(SectionCoverDao.class).clone();
        sectionCoverDaoConfig.initIdentityScope(type);

        sectionDetailDaoConfig = daoConfigMap.get(SectionDetailDao.class).clone();
        sectionDetailDaoConfig.initIdentityScope(type);

        sectionDocumentDaoConfig = daoConfigMap.get(SectionDocumentDao.class).clone();
        sectionDocumentDaoConfig.initIdentityScope(type);

        sectionDocumentItemDaoConfig = daoConfigMap.get(SectionDocumentItemDao.class).clone();
        sectionDocumentItemDaoConfig.initIdentityScope(type);

        sectionImprintDaoConfig = daoConfigMap.get(SectionImprintDao.class).clone();
        sectionImprintDaoConfig.initIdentityScope(type);

        sectionImprintEditorDaoConfig = daoConfigMap.get(SectionImprintEditorDao.class).clone();
        sectionImprintEditorDaoConfig.initIdentityScope(type);

        sectionLearningCenterDaoConfig = daoConfigMap.get(SectionLearningCenterDao.class).clone();
        sectionLearningCenterDaoConfig.initIdentityScope(type);

        sectionMainPointsDaoConfig = daoConfigMap.get(SectionMainPointsDao.class).clone();
        sectionMainPointsDaoConfig.initIdentityScope(type);

        sectionNameListDaoConfig = daoConfigMap.get(SectionNameListDao.class).clone();
        sectionNameListDaoConfig.initIdentityScope(type);

        sectionParagraphDaoConfig = daoConfigMap.get(SectionParagraphDao.class).clone();
        sectionParagraphDaoConfig.initIdentityScope(type);

        sectionPrefaceDaoConfig = daoConfigMap.get(SectionPrefaceDao.class).clone();
        sectionPrefaceDaoConfig.initIdentityScope(type);

        sectionPrefaceTitleDaoConfig = daoConfigMap.get(SectionPrefaceTitleDao.class).clone();
        sectionPrefaceTitleDaoConfig.initIdentityScope(type);

        sectionReferenceDaoConfig = daoConfigMap.get(SectionReferenceDao.class).clone();
        sectionReferenceDaoConfig.initIdentityScope(type);

        sectionShorthandDaoConfig = daoConfigMap.get(SectionShorthandDao.class).clone();
        sectionShorthandDaoConfig.initIdentityScope(type);

        sectionSummaryDaoConfig = daoConfigMap.get(SectionSummaryDao.class).clone();
        sectionSummaryDaoConfig.initIdentityScope(type);

        sectionSummaryChineseDaoConfig = daoConfigMap.get(SectionSummaryChineseDao.class).clone();
        sectionSummaryChineseDaoConfig.initIdentityScope(type);

        sectionSummaryEnglishDaoConfig = daoConfigMap.get(SectionSummaryEnglishDao.class).clone();
        sectionSummaryEnglishDaoConfig.initIdentityScope(type);

        sectionTranslateDaoConfig = daoConfigMap.get(SectionTranslateDao.class).clone();
        sectionTranslateDaoConfig.initIdentityScope(type);

        tableViewDaoConfig = daoConfigMap.get(TableViewDao.class).clone();
        tableViewDaoConfig.initIdentityScope(type);

        tDViewDaoConfig = daoConfigMap.get(TDViewDao.class).clone();
        tDViewDaoConfig.initIdentityScope(type);

        tRViewDaoConfig = daoConfigMap.get(TRViewDao.class).clone();
        tRViewDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        userBookDaoConfig = daoConfigMap.get(UserBookDao.class).clone();
        userBookDaoConfig.initIdentityScope(type);

        bookDao = new BookDao(bookDaoConfig, this);
        examDao = new ExamDao(examDaoConfig, this);
        authorDao = new AuthorDao(authorDaoConfig, this);
        authorItemDao = new AuthorItemDao(authorItemDaoConfig, this);
        authorItemContentsDao = new AuthorItemContentsDao(authorItemContentsDaoConfig, this);
        authorTitleDao = new AuthorTitleDao(authorTitleDaoConfig, this);
        chapterDao = new ChapterDao(chapterDaoConfig, this);
        collegesDao = new CollegesDao(collegesDaoConfig, this);
        combinationItemDao = new CombinationItemDao(combinationItemDaoConfig, this);
        committeeDao = new CommitteeDao(committeeDaoConfig, this);
        editorsDao = new EditorsDao(editorsDaoConfig, this);
        keyWordDao = new KeyWordDao(keyWordDaoConfig, this);
        localBookDao = new LocalBookDao(localBookDaoConfig, this);
        mediaBlockDao = new MediaBlockDao(mediaBlockDaoConfig, this);
        mediaPPTItemDao = new MediaPPTItemDao(mediaPPTItemDaoConfig, this);
        mediasDao = new MediasDao(mediasDaoConfig, this);
        mediaSequenceDao = new MediaSequenceDao(mediaSequenceDaoConfig, this);
        mediaSequencePicturesDao = new MediaSequencePicturesDao(mediaSequencePicturesDaoConfig, this);
        mediaStaticSequencePicturesDao = new MediaStaticSequencePicturesDao(mediaStaticSequencePicturesDaoConfig, this);
        mediaVideoDao = new MediaVideoDao(mediaVideoDaoConfig, this);
        paragraphDao = new ParagraphDao(paragraphDaoConfig, this);
        paragraphAuthorDao = new ParagraphAuthorDao(paragraphAuthorDaoConfig, this);
        sectionDao = new SectionDao(sectionDaoConfig, this);
        sectionAcknowledgementsDao = new SectionAcknowledgementsDao(sectionAcknowledgementsDaoConfig, this);
        sectionBackCoverDao = new SectionBackCoverDao(sectionBackCoverDaoConfig, this);
        sectionCaseSectionDao = new SectionCaseSectionDao(sectionCaseSectionDaoConfig, this);
        sectionCasesItemDao = new SectionCasesItemDao(sectionCasesItemDaoConfig, this);
        sectionCasesItemAuthorsDao = new SectionCasesItemAuthorsDao(sectionCasesItemAuthorsDaoConfig, this);
        sectionCETranslateDao = new SectionCETranslateDao(sectionCETranslateDaoConfig, this);
        sectionCoverDao = new SectionCoverDao(sectionCoverDaoConfig, this);
        sectionDetailDao = new SectionDetailDao(sectionDetailDaoConfig, this);
        sectionDocumentDao = new SectionDocumentDao(sectionDocumentDaoConfig, this);
        sectionDocumentItemDao = new SectionDocumentItemDao(sectionDocumentItemDaoConfig, this);
        sectionImprintDao = new SectionImprintDao(sectionImprintDaoConfig, this);
        sectionImprintEditorDao = new SectionImprintEditorDao(sectionImprintEditorDaoConfig, this);
        sectionLearningCenterDao = new SectionLearningCenterDao(sectionLearningCenterDaoConfig, this);
        sectionMainPointsDao = new SectionMainPointsDao(sectionMainPointsDaoConfig, this);
        sectionNameListDao = new SectionNameListDao(sectionNameListDaoConfig, this);
        sectionParagraphDao = new SectionParagraphDao(sectionParagraphDaoConfig, this);
        sectionPrefaceDao = new SectionPrefaceDao(sectionPrefaceDaoConfig, this);
        sectionPrefaceTitleDao = new SectionPrefaceTitleDao(sectionPrefaceTitleDaoConfig, this);
        sectionReferenceDao = new SectionReferenceDao(sectionReferenceDaoConfig, this);
        sectionShorthandDao = new SectionShorthandDao(sectionShorthandDaoConfig, this);
        sectionSummaryDao = new SectionSummaryDao(sectionSummaryDaoConfig, this);
        sectionSummaryChineseDao = new SectionSummaryChineseDao(sectionSummaryChineseDaoConfig, this);
        sectionSummaryEnglishDao = new SectionSummaryEnglishDao(sectionSummaryEnglishDaoConfig, this);
        sectionTranslateDao = new SectionTranslateDao(sectionTranslateDaoConfig, this);
        tableViewDao = new TableViewDao(tableViewDaoConfig, this);
        tDViewDao = new TDViewDao(tDViewDaoConfig, this);
        tRViewDao = new TRViewDao(tRViewDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        userBookDao = new UserBookDao(userBookDaoConfig, this);

        registerDao(Book.class, bookDao);
        registerDao(Exam.class, examDao);
        registerDao(Author.class, authorDao);
        registerDao(AuthorItem.class, authorItemDao);
        registerDao(AuthorItemContents.class, authorItemContentsDao);
        registerDao(AuthorTitle.class, authorTitleDao);
        registerDao(Chapter.class, chapterDao);
        registerDao(Colleges.class, collegesDao);
        registerDao(CombinationItem.class, combinationItemDao);
        registerDao(Committee.class, committeeDao);
        registerDao(Editors.class, editorsDao);
        registerDao(KeyWord.class, keyWordDao);
        registerDao(LocalBook.class, localBookDao);
        registerDao(MediaBlock.class, mediaBlockDao);
        registerDao(MediaPPTItem.class, mediaPPTItemDao);
        registerDao(Medias.class, mediasDao);
        registerDao(MediaSequence.class, mediaSequenceDao);
        registerDao(MediaSequencePictures.class, mediaSequencePicturesDao);
        registerDao(MediaStaticSequencePictures.class, mediaStaticSequencePicturesDao);
        registerDao(MediaVideo.class, mediaVideoDao);
        registerDao(Paragraph.class, paragraphDao);
        registerDao(ParagraphAuthor.class, paragraphAuthorDao);
        registerDao(Section.class, sectionDao);
        registerDao(SectionAcknowledgements.class, sectionAcknowledgementsDao);
        registerDao(SectionBackCover.class, sectionBackCoverDao);
        registerDao(SectionCaseSection.class, sectionCaseSectionDao);
        registerDao(SectionCasesItem.class, sectionCasesItemDao);
        registerDao(SectionCasesItemAuthors.class, sectionCasesItemAuthorsDao);
        registerDao(SectionCETranslate.class, sectionCETranslateDao);
        registerDao(SectionCover.class, sectionCoverDao);
        registerDao(SectionDetail.class, sectionDetailDao);
        registerDao(SectionDocument.class, sectionDocumentDao);
        registerDao(SectionDocumentItem.class, sectionDocumentItemDao);
        registerDao(SectionImprint.class, sectionImprintDao);
        registerDao(SectionImprintEditor.class, sectionImprintEditorDao);
        registerDao(SectionLearningCenter.class, sectionLearningCenterDao);
        registerDao(SectionMainPoints.class, sectionMainPointsDao);
        registerDao(SectionNameList.class, sectionNameListDao);
        registerDao(SectionParagraph.class, sectionParagraphDao);
        registerDao(SectionPreface.class, sectionPrefaceDao);
        registerDao(SectionPrefaceTitle.class, sectionPrefaceTitleDao);
        registerDao(SectionReference.class, sectionReferenceDao);
        registerDao(SectionShorthand.class, sectionShorthandDao);
        registerDao(SectionSummary.class, sectionSummaryDao);
        registerDao(SectionSummaryChinese.class, sectionSummaryChineseDao);
        registerDao(SectionSummaryEnglish.class, sectionSummaryEnglishDao);
        registerDao(SectionTranslate.class, sectionTranslateDao);
        registerDao(TableView.class, tableViewDao);
        registerDao(TDView.class, tDViewDao);
        registerDao(TRView.class, tRViewDao);
        registerDao(User.class, userDao);
        registerDao(UserBook.class, userBookDao);
    }
    
    public void clear() {
        bookDaoConfig.clearIdentityScope();
        examDaoConfig.clearIdentityScope();
        authorDaoConfig.clearIdentityScope();
        authorItemDaoConfig.clearIdentityScope();
        authorItemContentsDaoConfig.clearIdentityScope();
        authorTitleDaoConfig.clearIdentityScope();
        chapterDaoConfig.clearIdentityScope();
        collegesDaoConfig.clearIdentityScope();
        combinationItemDaoConfig.clearIdentityScope();
        committeeDaoConfig.clearIdentityScope();
        editorsDaoConfig.clearIdentityScope();
        keyWordDaoConfig.clearIdentityScope();
        localBookDaoConfig.clearIdentityScope();
        mediaBlockDaoConfig.clearIdentityScope();
        mediaPPTItemDaoConfig.clearIdentityScope();
        mediasDaoConfig.clearIdentityScope();
        mediaSequenceDaoConfig.clearIdentityScope();
        mediaSequencePicturesDaoConfig.clearIdentityScope();
        mediaStaticSequencePicturesDaoConfig.clearIdentityScope();
        mediaVideoDaoConfig.clearIdentityScope();
        paragraphDaoConfig.clearIdentityScope();
        paragraphAuthorDaoConfig.clearIdentityScope();
        sectionDaoConfig.clearIdentityScope();
        sectionAcknowledgementsDaoConfig.clearIdentityScope();
        sectionBackCoverDaoConfig.clearIdentityScope();
        sectionCaseSectionDaoConfig.clearIdentityScope();
        sectionCasesItemDaoConfig.clearIdentityScope();
        sectionCasesItemAuthorsDaoConfig.clearIdentityScope();
        sectionCETranslateDaoConfig.clearIdentityScope();
        sectionCoverDaoConfig.clearIdentityScope();
        sectionDetailDaoConfig.clearIdentityScope();
        sectionDocumentDaoConfig.clearIdentityScope();
        sectionDocumentItemDaoConfig.clearIdentityScope();
        sectionImprintDaoConfig.clearIdentityScope();
        sectionImprintEditorDaoConfig.clearIdentityScope();
        sectionLearningCenterDaoConfig.clearIdentityScope();
        sectionMainPointsDaoConfig.clearIdentityScope();
        sectionNameListDaoConfig.clearIdentityScope();
        sectionParagraphDaoConfig.clearIdentityScope();
        sectionPrefaceDaoConfig.clearIdentityScope();
        sectionPrefaceTitleDaoConfig.clearIdentityScope();
        sectionReferenceDaoConfig.clearIdentityScope();
        sectionShorthandDaoConfig.clearIdentityScope();
        sectionSummaryDaoConfig.clearIdentityScope();
        sectionSummaryChineseDaoConfig.clearIdentityScope();
        sectionSummaryEnglishDaoConfig.clearIdentityScope();
        sectionTranslateDaoConfig.clearIdentityScope();
        tableViewDaoConfig.clearIdentityScope();
        tDViewDaoConfig.clearIdentityScope();
        tRViewDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        userBookDaoConfig.clearIdentityScope();
    }

    public BookDao getBookDao() {
        return bookDao;
    }

    public ExamDao getExamDao() {
        return examDao;
    }

    public AuthorDao getAuthorDao() {
        return authorDao;
    }

    public AuthorItemDao getAuthorItemDao() {
        return authorItemDao;
    }

    public AuthorItemContentsDao getAuthorItemContentsDao() {
        return authorItemContentsDao;
    }

    public AuthorTitleDao getAuthorTitleDao() {
        return authorTitleDao;
    }

    public ChapterDao getChapterDao() {
        return chapterDao;
    }

    public CollegesDao getCollegesDao() {
        return collegesDao;
    }

    public CombinationItemDao getCombinationItemDao() {
        return combinationItemDao;
    }

    public CommitteeDao getCommitteeDao() {
        return committeeDao;
    }

    public EditorsDao getEditorsDao() {
        return editorsDao;
    }

    public KeyWordDao getKeyWordDao() {
        return keyWordDao;
    }

    public LocalBookDao getLocalBookDao() {
        return localBookDao;
    }

    public MediaBlockDao getMediaBlockDao() {
        return mediaBlockDao;
    }

    public MediaPPTItemDao getMediaPPTItemDao() {
        return mediaPPTItemDao;
    }

    public MediasDao getMediasDao() {
        return mediasDao;
    }

    public MediaSequenceDao getMediaSequenceDao() {
        return mediaSequenceDao;
    }

    public MediaSequencePicturesDao getMediaSequencePicturesDao() {
        return mediaSequencePicturesDao;
    }

    public MediaStaticSequencePicturesDao getMediaStaticSequencePicturesDao() {
        return mediaStaticSequencePicturesDao;
    }

    public MediaVideoDao getMediaVideoDao() {
        return mediaVideoDao;
    }

    public ParagraphDao getParagraphDao() {
        return paragraphDao;
    }

    public ParagraphAuthorDao getParagraphAuthorDao() {
        return paragraphAuthorDao;
    }

    public SectionDao getSectionDao() {
        return sectionDao;
    }

    public SectionAcknowledgementsDao getSectionAcknowledgementsDao() {
        return sectionAcknowledgementsDao;
    }

    public SectionBackCoverDao getSectionBackCoverDao() {
        return sectionBackCoverDao;
    }

    public SectionCaseSectionDao getSectionCaseSectionDao() {
        return sectionCaseSectionDao;
    }

    public SectionCasesItemDao getSectionCasesItemDao() {
        return sectionCasesItemDao;
    }

    public SectionCasesItemAuthorsDao getSectionCasesItemAuthorsDao() {
        return sectionCasesItemAuthorsDao;
    }

    public SectionCETranslateDao getSectionCETranslateDao() {
        return sectionCETranslateDao;
    }

    public SectionCoverDao getSectionCoverDao() {
        return sectionCoverDao;
    }

    public SectionDetailDao getSectionDetailDao() {
        return sectionDetailDao;
    }

    public SectionDocumentDao getSectionDocumentDao() {
        return sectionDocumentDao;
    }

    public SectionDocumentItemDao getSectionDocumentItemDao() {
        return sectionDocumentItemDao;
    }

    public SectionImprintDao getSectionImprintDao() {
        return sectionImprintDao;
    }

    public SectionImprintEditorDao getSectionImprintEditorDao() {
        return sectionImprintEditorDao;
    }

    public SectionLearningCenterDao getSectionLearningCenterDao() {
        return sectionLearningCenterDao;
    }

    public SectionMainPointsDao getSectionMainPointsDao() {
        return sectionMainPointsDao;
    }

    public SectionNameListDao getSectionNameListDao() {
        return sectionNameListDao;
    }

    public SectionParagraphDao getSectionParagraphDao() {
        return sectionParagraphDao;
    }

    public SectionPrefaceDao getSectionPrefaceDao() {
        return sectionPrefaceDao;
    }

    public SectionPrefaceTitleDao getSectionPrefaceTitleDao() {
        return sectionPrefaceTitleDao;
    }

    public SectionReferenceDao getSectionReferenceDao() {
        return sectionReferenceDao;
    }

    public SectionShorthandDao getSectionShorthandDao() {
        return sectionShorthandDao;
    }

    public SectionSummaryDao getSectionSummaryDao() {
        return sectionSummaryDao;
    }

    public SectionSummaryChineseDao getSectionSummaryChineseDao() {
        return sectionSummaryChineseDao;
    }

    public SectionSummaryEnglishDao getSectionSummaryEnglishDao() {
        return sectionSummaryEnglishDao;
    }

    public SectionTranslateDao getSectionTranslateDao() {
        return sectionTranslateDao;
    }

    public TableViewDao getTableViewDao() {
        return tableViewDao;
    }

    public TDViewDao getTDViewDao() {
        return tDViewDao;
    }

    public TRViewDao getTRViewDao() {
        return tRViewDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public UserBookDao getUserBookDao() {
        return userBookDao;
    }

}
