package com.mvw.medicalvisualteaching.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mvw.medicalvisualteaching.bean.offlinebook.Editors;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "Editors".
*/
public class EditorsDao extends AbstractDao<Editors, Void> {

    public static final String TABLENAME = "Editors";

    /**
     * Properties of entity Editors.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", false, "id");
        public final static Property College = new Property(1, String.class, "college", false, "college");
        public final static Property Name = new Property(2, String.class, "name", false, "name ");
        public final static Property DutyType = new Property(3, String.class, "dutyType", false, "dutyType");
        public final static Property Subject = new Property(4, String.class, "subject", false, "subject ");
    }


    public EditorsDao(DaoConfig config) {
        super(config);
    }
    
    public EditorsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Editors entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String college = entity.getCollege();
        if (college != null) {
            stmt.bindString(2, college);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String dutyType = entity.getDutyType();
        if (dutyType != null) {
            stmt.bindString(4, dutyType);
        }
 
        String subject = entity.getSubject();
        if (subject != null) {
            stmt.bindString(5, subject);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Editors entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String college = entity.getCollege();
        if (college != null) {
            stmt.bindString(2, college);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String dutyType = entity.getDutyType();
        if (dutyType != null) {
            stmt.bindString(4, dutyType);
        }
 
        String subject = entity.getSubject();
        if (subject != null) {
            stmt.bindString(5, subject);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Editors readEntity(Cursor cursor, int offset) {
        Editors entity = new Editors( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // college
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // dutyType
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // subject
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Editors entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setCollege(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDutyType(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSubject(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Editors entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Editors entity) {
        return null;
    }

    @Override
    public boolean hasKey(Editors entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
