package com.mvw.medicalvisualteaching.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mvw.medicalvisualteaching.bean.offlinebook.MediaBlock;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MediaBlock".
*/
public class MediaBlockDao extends AbstractDao<MediaBlock, Void> {

    public static final String TABLENAME = "MediaBlock";

    /**
     * Properties of entity MediaBlock.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", false, "id");
        public final static Property Name = new Property(1, String.class, "name", false, "name");
        public final static Property Order = new Property(2, String.class, "order", false, "f_order");
        public final static Property Paragraph_id = new Property(3, String.class, "paragraph_id", false, "paragraph_id");
    }


    public MediaBlockDao(DaoConfig config) {
        super(config);
    }
    
    public MediaBlockDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MediaBlock entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String order = entity.getOrder();
        if (order != null) {
            stmt.bindString(3, order);
        }
 
        String paragraph_id = entity.getParagraph_id();
        if (paragraph_id != null) {
            stmt.bindString(4, paragraph_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MediaBlock entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String order = entity.getOrder();
        if (order != null) {
            stmt.bindString(3, order);
        }
 
        String paragraph_id = entity.getParagraph_id();
        if (paragraph_id != null) {
            stmt.bindString(4, paragraph_id);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public MediaBlock readEntity(Cursor cursor, int offset) {
        MediaBlock entity = new MediaBlock( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // order
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // paragraph_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MediaBlock entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setOrder(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setParagraph_id(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(MediaBlock entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(MediaBlock entity) {
        return null;
    }

    @Override
    public boolean hasKey(MediaBlock entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
