package com.mvw.medicalvisualteaching.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mvw.medicalvisualteaching.bean.offlinebook.MediaSequencePictures;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MediaSequence_pictures".
*/
public class MediaSequencePicturesDao extends AbstractDao<MediaSequencePictures, Void> {

    public static final String TABLENAME = "MediaSequence_pictures";

    /**
     * Properties of entity MediaSequencePictures.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property MediaSequence_id = new Property(0, String.class, "MediaSequence_id", false, "MediaSequence_id");
        public final static Property Pictures = new Property(1, String.class, "pictures", false, "pictures");
    }


    public MediaSequencePicturesDao(DaoConfig config) {
        super(config);
    }
    
    public MediaSequencePicturesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MediaSequencePictures entity) {
        stmt.clearBindings();
 
        String MediaSequence_id = entity.getMediaSequence_id();
        if (MediaSequence_id != null) {
            stmt.bindString(1, MediaSequence_id);
        }
 
        String pictures = entity.getPictures();
        if (pictures != null) {
            stmt.bindString(2, pictures);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MediaSequencePictures entity) {
        stmt.clearBindings();
 
        String MediaSequence_id = entity.getMediaSequence_id();
        if (MediaSequence_id != null) {
            stmt.bindString(1, MediaSequence_id);
        }
 
        String pictures = entity.getPictures();
        if (pictures != null) {
            stmt.bindString(2, pictures);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public MediaSequencePictures readEntity(Cursor cursor, int offset) {
        MediaSequencePictures entity = new MediaSequencePictures( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // MediaSequence_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // pictures
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MediaSequencePictures entity, int offset) {
        entity.setMediaSequence_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setPictures(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(MediaSequencePictures entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(MediaSequencePictures entity) {
        return null;
    }

    @Override
    public boolean hasKey(MediaSequencePictures entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
