package com.mvw.medicalvisualteaching.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mvw.medicalvisualteaching.bean.offlinebook.SectionImprintEditor;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "Imprint_editors".
*/
public class SectionImprintEditorDao extends AbstractDao<SectionImprintEditor, Void> {

    public static final String TABLENAME = "Imprint_editors";

    /**
     * Properties of entity SectionImprintEditor.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Imprint_id = new Property(0, String.class, "Imprint_id", false, "Imprint_id");
        public final static Property Editors = new Property(1, String.class, "editors", false, "editors");
    }


    public SectionImprintEditorDao(DaoConfig config) {
        super(config);
    }
    
    public SectionImprintEditorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SectionImprintEditor entity) {
        stmt.clearBindings();
 
        String Imprint_id = entity.getImprint_id();
        if (Imprint_id != null) {
            stmt.bindString(1, Imprint_id);
        }
 
        String editors = entity.getEditors();
        if (editors != null) {
            stmt.bindString(2, editors);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SectionImprintEditor entity) {
        stmt.clearBindings();
 
        String Imprint_id = entity.getImprint_id();
        if (Imprint_id != null) {
            stmt.bindString(1, Imprint_id);
        }
 
        String editors = entity.getEditors();
        if (editors != null) {
            stmt.bindString(2, editors);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public SectionImprintEditor readEntity(Cursor cursor, int offset) {
        SectionImprintEditor entity = new SectionImprintEditor( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // Imprint_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // editors
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SectionImprintEditor entity, int offset) {
        entity.setImprint_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setEditors(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(SectionImprintEditor entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(SectionImprintEditor entity) {
        return null;
    }

    @Override
    public boolean hasKey(SectionImprintEditor entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
