package com.mvw.medicalvisualteaching.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mvw.medicalvisualteaching.bean.offlinebook.SectionPrefaceTitle;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "Preface_titles".
*/
public class SectionPrefaceTitleDao extends AbstractDao<SectionPrefaceTitle, Void> {

    public static final String TABLENAME = "Preface_titles";

    /**
     * Properties of entity SectionPrefaceTitle.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Preface_id = new Property(0, String.class, "Preface_id", false, "Preface_id");
        public final static Property Titles = new Property(1, String.class, "titles", false, "titles");
    }


    public SectionPrefaceTitleDao(DaoConfig config) {
        super(config);
    }
    
    public SectionPrefaceTitleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SectionPrefaceTitle entity) {
        stmt.clearBindings();
 
        String Preface_id = entity.getPreface_id();
        if (Preface_id != null) {
            stmt.bindString(1, Preface_id);
        }
 
        String titles = entity.getTitles();
        if (titles != null) {
            stmt.bindString(2, titles);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SectionPrefaceTitle entity) {
        stmt.clearBindings();
 
        String Preface_id = entity.getPreface_id();
        if (Preface_id != null) {
            stmt.bindString(1, Preface_id);
        }
 
        String titles = entity.getTitles();
        if (titles != null) {
            stmt.bindString(2, titles);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public SectionPrefaceTitle readEntity(Cursor cursor, int offset) {
        SectionPrefaceTitle entity = new SectionPrefaceTitle( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // Preface_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // titles
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SectionPrefaceTitle entity, int offset) {
        entity.setPreface_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTitles(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(SectionPrefaceTitle entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(SectionPrefaceTitle entity) {
        return null;
    }

    @Override
    public boolean hasKey(SectionPrefaceTitle entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
