package com.mvw.medicalvisualteaching.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mvw.medicalvisualteaching.bean.offlinebook.SectionSummary;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "Section_Summary".
*/
public class SectionSummaryDao extends AbstractDao<SectionSummary, Void> {

    public static final String TABLENAME = "Section_Summary";

    /**
     * Properties of entity SectionSummary.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", false, "id");
        public final static Property Audio = new Property(1, String.class, "audio", false, "audio");
    }


    public SectionSummaryDao(DaoConfig config) {
        super(config);
    }
    
    public SectionSummaryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SectionSummary entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String audio = entity.getAudio();
        if (audio != null) {
            stmt.bindString(2, audio);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SectionSummary entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String audio = entity.getAudio();
        if (audio != null) {
            stmt.bindString(2, audio);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public SectionSummary readEntity(Cursor cursor, int offset) {
        SectionSummary entity = new SectionSummary( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // audio
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SectionSummary entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setAudio(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(SectionSummary entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(SectionSummary entity) {
        return null;
    }

    @Override
    public boolean hasKey(SectionSummary entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
