package com.mvw.medicalvisualteaching.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mvw.medicalvisualteaching.bean.offlinebook.SectionShorthand;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "Section_Shorthand".
*/
public class SectionShorthandDao extends AbstractDao<SectionShorthand, Void> {

    public static final String TABLENAME = "Section_Shorthand";

    /**
     * Properties of entity SectionShorthand.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", false, "ID");
        public final static Property LearningCenter_id = new Property(1, String.class, "learningCenter_id", false, "learningCenter_id");
    }


    public SectionShorthandDao(DaoConfig config) {
        super(config);
    }
    
    public SectionShorthandDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SectionShorthand entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String learningCenter_id = entity.getLearningCenter_id();
        if (learningCenter_id != null) {
            stmt.bindString(2, learningCenter_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SectionShorthand entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String learningCenter_id = entity.getLearningCenter_id();
        if (learningCenter_id != null) {
            stmt.bindString(2, learningCenter_id);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public SectionShorthand readEntity(Cursor cursor, int offset) {
        SectionShorthand entity = new SectionShorthand( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // learningCenter_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SectionShorthand entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setLearningCenter_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(SectionShorthand entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(SectionShorthand entity) {
        return null;
    }

    @Override
    public boolean hasKey(SectionShorthand entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
