package com.mvw.medicalvisualteaching.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mvw.medicalvisualteaching.bean.offlinebook.SectionDetail;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "section_detail".
*/
public class SectionDetailDao extends AbstractDao<SectionDetail, Void> {

    public static final String TABLENAME = "section_detail";

    /**
     * Properties of entity SectionDetail.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", false, "id");
        public final static Property Extend = new Property(1, String.class, "extend", false, "extend");
    }


    public SectionDetailDao(DaoConfig config) {
        super(config);
    }
    
    public SectionDetailDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SectionDetail entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String extend = entity.getExtend();
        if (extend != null) {
            stmt.bindString(2, extend);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SectionDetail entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String extend = entity.getExtend();
        if (extend != null) {
            stmt.bindString(2, extend);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public SectionDetail readEntity(Cursor cursor, int offset) {
        SectionDetail entity = new SectionDetail( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // extend
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SectionDetail entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setExtend(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(SectionDetail entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(SectionDetail entity) {
        return null;
    }

    @Override
    public boolean hasKey(SectionDetail entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
