package com.mvw.medicalvisualteaching.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mvw.medicalvisualteaching.bean.offlinebook.SectionSummaryChinese;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "Summary_chinese".
*/
public class SectionSummaryChineseDao extends AbstractDao<SectionSummaryChinese, Void> {

    public static final String TABLENAME = "Summary_chinese";

    /**
     * Properties of entity SectionSummaryChinese.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Summary_id = new Property(0, String.class, "Summary_id", false, "Summary_id");
        public final static Property Chinese = new Property(1, String.class, "chinese", false, "chinese");
    }


    public SectionSummaryChineseDao(DaoConfig config) {
        super(config);
    }
    
    public SectionSummaryChineseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SectionSummaryChinese entity) {
        stmt.clearBindings();
 
        String Summary_id = entity.getSummary_id();
        if (Summary_id != null) {
            stmt.bindString(1, Summary_id);
        }
 
        String chinese = entity.getChinese();
        if (chinese != null) {
            stmt.bindString(2, chinese);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SectionSummaryChinese entity) {
        stmt.clearBindings();
 
        String Summary_id = entity.getSummary_id();
        if (Summary_id != null) {
            stmt.bindString(1, Summary_id);
        }
 
        String chinese = entity.getChinese();
        if (chinese != null) {
            stmt.bindString(2, chinese);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public SectionSummaryChinese readEntity(Cursor cursor, int offset) {
        SectionSummaryChinese entity = new SectionSummaryChinese( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // Summary_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // chinese
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SectionSummaryChinese entity, int offset) {
        entity.setSummary_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setChinese(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(SectionSummaryChinese entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(SectionSummaryChinese entity) {
        return null;
    }

    @Override
    public boolean hasKey(SectionSummaryChinese entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
