package com.mvw.medicalvisualteaching.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mvw.medicalvisualteaching.bean.offlinebook.SectionCasesItemAuthors;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CasesItem_Author".
*/
public class SectionCasesItemAuthorsDao extends AbstractDao<SectionCasesItemAuthors, Void> {

    public static final String TABLENAME = "CasesItem_Author";

    /**
     * Properties of entity SectionCasesItemAuthors.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Cases_id = new Property(0, String.class, "cases_id", false, "CasesItem_id");
        public final static Property Authors_id = new Property(1, String.class, "authors_id", false, "authors_id");
    }


    public SectionCasesItemAuthorsDao(DaoConfig config) {
        super(config);
    }
    
    public SectionCasesItemAuthorsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SectionCasesItemAuthors entity) {
        stmt.clearBindings();
 
        String cases_id = entity.getCases_id();
        if (cases_id != null) {
            stmt.bindString(1, cases_id);
        }
 
        String authors_id = entity.getAuthors_id();
        if (authors_id != null) {
            stmt.bindString(2, authors_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SectionCasesItemAuthors entity) {
        stmt.clearBindings();
 
        String cases_id = entity.getCases_id();
        if (cases_id != null) {
            stmt.bindString(1, cases_id);
        }
 
        String authors_id = entity.getAuthors_id();
        if (authors_id != null) {
            stmt.bindString(2, authors_id);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public SectionCasesItemAuthors readEntity(Cursor cursor, int offset) {
        SectionCasesItemAuthors entity = new SectionCasesItemAuthors( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // cases_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // authors_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SectionCasesItemAuthors entity, int offset) {
        entity.setCases_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setAuthors_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(SectionCasesItemAuthors entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(SectionCasesItemAuthors entity) {
        return null;
    }

    @Override
    public boolean hasKey(SectionCasesItemAuthors entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
