package com.mvw.medicalvisualteaching.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mvw.medicalvisualteaching.bean.offlinebook.SectionPreface;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "Section_Preface".
*/
public class SectionPrefaceDao extends AbstractDao<SectionPreface, Void> {

    public static final String TABLENAME = "Section_Preface";

    /**
     * Properties of entity SectionPreface.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", false, "ID");
        public final static Property Mark = new Property(1, String.class, "mark", false, "mark");
        public final static Property Mark1 = new Property(2, String.class, "mark1", false, "mark1");
        public final static Property Timestamp = new Property(3, String.class, "timestamp", false, "timestamp");
    }


    public SectionPrefaceDao(DaoConfig config) {
        super(config);
    }
    
    public SectionPrefaceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SectionPreface entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String mark = entity.getMark();
        if (mark != null) {
            stmt.bindString(2, mark);
        }
 
        String mark1 = entity.getMark1();
        if (mark1 != null) {
            stmt.bindString(3, mark1);
        }
 
        String timestamp = entity.getTimestamp();
        if (timestamp != null) {
            stmt.bindString(4, timestamp);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SectionPreface entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String mark = entity.getMark();
        if (mark != null) {
            stmt.bindString(2, mark);
        }
 
        String mark1 = entity.getMark1();
        if (mark1 != null) {
            stmt.bindString(3, mark1);
        }
 
        String timestamp = entity.getTimestamp();
        if (timestamp != null) {
            stmt.bindString(4, timestamp);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public SectionPreface readEntity(Cursor cursor, int offset) {
        SectionPreface entity = new SectionPreface( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // mark
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // mark1
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // timestamp
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SectionPreface entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setMark(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMark1(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTimestamp(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(SectionPreface entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(SectionPreface entity) {
        return null;
    }

    @Override
    public boolean hasKey(SectionPreface entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
