package com.mvw.medicalvisualteaching.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mvw.medicalvisualteaching.bean.offlinebook.TableView;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TableView".
*/
public class TableViewDao extends AbstractDao<TableView, Void> {

    public static final String TABLENAME = "TableView";

    /**
     * Properties of entity TableView.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", false, "id");
        public final static Property RowNum = new Property(1, String.class, "rowNum", false, "rowNum");
        public final static Property ColNum = new Property(2, String.class, "colNum", false, "colNum");
        public final static Property TableIndex = new Property(3, String.class, "tableIndex", false, "tableIndex");
        public final static Property TableName = new Property(4, String.class, "tableName", false, "tableName");
        public final static Property Paragraph_id = new Property(5, String.class, "paragraph_id", false, "paragraph_id");
    }


    public TableViewDao(DaoConfig config) {
        super(config);
    }
    
    public TableViewDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TableView entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String rowNum = entity.getRowNum();
        if (rowNum != null) {
            stmt.bindString(2, rowNum);
        }
 
        String colNum = entity.getColNum();
        if (colNum != null) {
            stmt.bindString(3, colNum);
        }
 
        String tableIndex = entity.getTableIndex();
        if (tableIndex != null) {
            stmt.bindString(4, tableIndex);
        }
 
        String tableName = entity.getTableName();
        if (tableName != null) {
            stmt.bindString(5, tableName);
        }
 
        String paragraph_id = entity.getParagraph_id();
        if (paragraph_id != null) {
            stmt.bindString(6, paragraph_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TableView entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String rowNum = entity.getRowNum();
        if (rowNum != null) {
            stmt.bindString(2, rowNum);
        }
 
        String colNum = entity.getColNum();
        if (colNum != null) {
            stmt.bindString(3, colNum);
        }
 
        String tableIndex = entity.getTableIndex();
        if (tableIndex != null) {
            stmt.bindString(4, tableIndex);
        }
 
        String tableName = entity.getTableName();
        if (tableName != null) {
            stmt.bindString(5, tableName);
        }
 
        String paragraph_id = entity.getParagraph_id();
        if (paragraph_id != null) {
            stmt.bindString(6, paragraph_id);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public TableView readEntity(Cursor cursor, int offset) {
        TableView entity = new TableView( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // rowNum
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // colNum
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // tableIndex
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // tableName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // paragraph_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TableView entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setRowNum(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setColNum(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTableIndex(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTableName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setParagraph_id(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(TableView entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(TableView entity) {
        return null;
    }

    @Override
    public boolean hasKey(TableView entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
